version: '3'
services:
  mysql-container:
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demodb
    volumes:
      - /containers/mysql/db1
    ports:
      - 3307:3306
#    networks:
#      - backend
  spring-docker-container:
    image: spring-docker-app-image
    env_file: .env
    environment:
      - USER_EMAIL=$USER_EMAIL
      - PASSWORD_EMAIL=$PASSWORD_EMAIL
      - GOOGLE_APP_ID=$GOOGLE_APP_ID
      - GOOGLE_APP_SECRET=$GOOGLE_APP_SECRET
      - SLACK_TOKEN=$SLACK_TOKEN
      - DB_LINK=$DB_LINK
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 8088:8080
    volumes:
      - /containers/spring-app-jpa


